// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5k2yIv18tyeMBGSKtOVvI7bBgDt3W6Uk',
    appId: '1:679848708629:web:9dcf2263974e24e7901c1c',
    messagingSenderId: '679848708629',
    projectId: 'e-libs',
    authDomain: 'e-libs.firebaseapp.com',
    storageBucket: 'e-libs.firebasestorage.app',
    measurementId: 'G-Z5M0P5PTZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmjS9EhC5JqQ7BrgdmGDpisU-qCtotUgU',
    appId: '1:679848708629:android:465576b148f54acd901c1c',
    messagingSenderId: '679848708629',
    projectId: 'e-libs',
    storageBucket: 'e-libs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl6DRUvXcZjMjvbTlojoHd1Gd1jAsltkI',
    appId: '1:679848708629:ios:6952247d6018e970901c1c',
    messagingSenderId: '679848708629',
    projectId: 'e-libs',
    storageBucket: 'e-libs.firebasestorage.app',
    iosBundleId: 'com.example.eperpusFullApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl6DRUvXcZjMjvbTlojoHd1Gd1jAsltkI',
    appId: '1:679848708629:ios:6952247d6018e970901c1c',
    messagingSenderId: '679848708629',
    projectId: 'e-libs',
    storageBucket: 'e-libs.firebasestorage.app',
    iosBundleId: 'com.example.eperpusFullApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5k2yIv18tyeMBGSKtOVvI7bBgDt3W6Uk',
    appId: '1:679848708629:web:d0e0dc13780d5364901c1c',
    messagingSenderId: '679848708629',
    projectId: 'e-libs',
    authDomain: 'e-libs.firebaseapp.com',
    storageBucket: 'e-libs.firebasestorage.app',
    measurementId: 'G-YJYNMGXNT9',
  );
}
